//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFILDownloader.Properties
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MFILDownloader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BNUpdate
        {
            get
            {
                object obj = ResourceManager.GetObject("BNUpdate", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to wow-pod-retail/CN/14250.streaming/wow-14250-9B22BD689F5A2FABB7C524D878C48CFF.mfil
        ///wow-pod-retail/CN/14250.streaming/wow-15354-D4A749CAF464B282987A39C2F6FC4D43.mfil
        ///wow-pod-retail/EU/12911.streaming/wow-13329-0658AFCDDF4D212A872B108F25947FA4.mfil
        ///wow-pod-retail/EU/12911.streaming/wow-13596-182577F9BEBE85C7AAA438AC1A6CCF1D.mfil
        ///wow-pod-retail/EU/12911.streaming/wow-13623-564D07B657C3DD8DDAEAF5B8C08536F3.mfil
        ///wow-pod-retail/EU/12911.streaming/wow-13914-9E88FE241FD62F2024EE40547E21E324.mfil
        ///wow-pod-retail [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mfils
        {
            get
            {
                return ResourceManager.GetString("mfils", resourceCulture);
            }
        }
    }
}
